language: node_js
node_js:
  - 14
install:
  - cd Code/backend
  - echo "installing"
  - npm install nodemailer
  - npm install
  - npx nodemon &
script:
  - echo "running tests"
  - npm test
after_success: npm test -- --coverage

